version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "10000:${PORT:-10000}"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=10000
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - ./.n8n:/home/node/.n8n
