version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "${PORT:-5678}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=n8n-docker.onrender.com
      - WEBHOOK_URL=https://n8n-docker.onrender.com/
      - GENERIC_TIMEZONE=America/Sao_Paulo
