version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    build: .
    depends_on:
      - postgres
    environment:
      # Map to local port for development
      PORT: 5678
      N8N_PROTOCOL: http
      # Use Postgres for persistence
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      DB_POSTGRESDB_SCHEMA: public
      # required encryption key
      N8N_ENCRYPTION_KEY: local-dev-encryption-key-change-me
      GENERIC_TIMEZONE: America/Sao_Paulo
    ports:
      - "5678:5678"

volumes:
  pgdata:
