services:
  - type: web
    name: n8n-docker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_HOST
        value: n8n-docker.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://n8n-docker.onrender.com/
